### ISSUE TITLE
pumpkin heads for snow golems and grumm

### ISSUE THREAD

**Issue by machinesmith42** [EvModder/DropHeads#10]
I think that the snow golem should drop a pumpkin had and it's grumm versions dropping upside down one.

**Comment by machinesmith42** [comment]
#13

**Comment by machinesmith42** [comment]
missing grumm

**Comment by EvModder** [comment]
This would also apply to hostile mobs that spawn with pumpkins during Halloween?
I feel this feature seems a bit too much of a stretch, ...
What about zombies wearing iron helmets? The helmet texture could also be added to the head.

What I mean is, I feel like the pumpkin isn't a "Head", more of just a "Mask"... and it might make more sense to drop an actual pumpkin block vs. a pumpkin head item.

**Comment by machinesmith42** [comment]
Ah thought that since it is grummable it would count
