### ISSUE TITLE
help getting heads to drop

### ISSUE THREAD

**Issue by NBS-Paste** [EvModder/DropHeads#101]
heads used to drop but now they don't. in the console it says dropheads.canloosehead=false. how can i make it become true?

**Comment by EvModder** [comment]
depends on what permission plugin you use - most of them have a way to set that permission to true for specific players or groups.

It is true by default BTW, so if it is false in the console that means your permission plugin is currently overriding the default value (true) with false

**Comment by NBS-Paste** [comment]
Thanks, got it working again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
