### ISSUE TITLE
Drop Heads 1.20.6 error

### ISSUE THREAD

**Issue by blue-pinapple** [EvModder/DropHeads#109]
I understand you might be busy but I have run into [this]( https://mclo.gs/bLJ6ubz#L2306 ) error after updating to 1.20.6

My server is being run on Aternos (a free hosting service) and I was just wondering if you were able to give a timeline for support of 1.20.6

**Comment by EvModder** [comment]
Sorry for the super-late reply! - For some reason I'm not getting push notifications from GitHub anymore, thanks Microsoft.

The latest release on Bukkit.com (from 2024-05-18), [DropHeads v3.9.4](https://dev.bukkit.org/projects/dropheads/files/5352763), should support 1.20.6
