### ISSUE TITLE
Error in latest beta version

### ISSUE THREAD

**Issue by pjindras** [EvModder/DropHeads#114]
<html>
<body>

[04:55:35] [Server thread/WARN]: java.lang.RuntimeException: no class found: net.minecraft.world.item.component.CustomData
1891 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.EvLib.extras.ReflectionUtils.getRefClass(ReflectionUtils.java:99)
1892 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:39)
1893 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:144)
1894 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:603)
1895 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:725)
1896 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:835)
1897 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:708)
1898 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:732)
1899 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:154)
1900 | [04:55:35] [Server thread/WARN]: 	at DropHeads.jar//net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:289)
1901 | [04:55:35] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72)
1902 | [04:55:35] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68)
1903 | [04:55:35] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
1904 | [04:55:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
1905 | [04:55:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:996)
1906 | [04:55:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:982)
1907 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.world.entity.decoration.EntityArmorStand.kill(EntityArmorStand.java:778)
1908 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.world.entity.decoration.EntityArmorStand.al(EntityArmorStand.java:772)
1909 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.world.entity.decoration.EntityArmorStand.a(EntityArmorStand.java:535)
1910 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1372)
1911 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2427)
1912 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2913)
1913 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
1914 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
1915 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2835)
1916 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
1917 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
1918 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
1919 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
1920 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:150)
1921 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
1922 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1471)
1923 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:181)
1924 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
1925 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1449)
1926 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1377)
1927 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
1928 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1354)
1929 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1244)
1930 | [04:55:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308)
1931 | [04:55:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
1932 | [04:55:35] [Server thread/WARN]:
1933

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by pjindras** [comment]
+ this ones are spamming

https://mclo.gs/s64KUxL

**Comment by EvModder** [comment]
What version of Minecraft and what version of DropHeads is it on?

**Comment by pjindras** [comment]
DropHeads v3.9.5 and 1.21

**Comment by EvModder** [comment]
Hmm, I may have fixed it in the lastest dev version, but not 100% sure since I didn't have the issue occurring for me in either version. But if you are able to,[ try out this (v3.9.6)](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.9.6.jar) and let me know if it still spams

**Comment by pjindras** [comment]
It seems to be fixed
