### ISSUE TITLE
after this update the heads in the plugin stopped working: https://hub.spigotmc.org/jira/browse/SPIGOT-7873

### ISSUE THREAD

**Issue by thiagogebrimm** [EvModder/DropHeads#116]
https://hub.spigotmc.org/jira/browse/SPIGOT-7873

**Comment by thiagogebrimm** [comment]
![image](https://github.com/user-attachments/assets/d8678225-cd2c-448c-968d-116f1e085341)

**Comment by EvModder** [comment]
For DropHeads v3.9.7 or v3.9.8?

**Comment by thiagogebrimm** [comment]
ops... in 3.9.8 works kkk
