### ISSUE TITLE
1.21 Player head creation has changed?

### ISSUE THREAD

**Issue by SethXB** [EvModder/DropHeads#118]
I went through a bunch of big fixing with another dev. They have a plugin that can create heads to use as custom ores. I get an error in console relating to dropheads anytime a custom head is dropped on the ground. Here is the error, I would love to see a fix for this!! For now I will have to put dropheads on hold to find another solution. But I love this plugin.
[logs.txt](https://github.com/user-attachments/files/17354437/logs.txt)

**Comment by EvModder** [comment]
NP, I'll look into it.
Seems a whole slew of random errors have started appearing in the current minor version (1.21.1), but I should be able to get them all resolved soon

**Comment by SethXB** [comment]
Yea mojang sure loves to throw in new systems.. But sounds good ill be on the lookout thank you!

**Comment by EvModder** [comment]
I forgot to reply here after my last message but the latest version of the plugin should work correctly without the head creation errors.

feel free to ping me and/or reopen this bug report though if  you're still seeing the issue
