### ISSUE TITLE
Old baby pigman

### ISSUE THREAD

**Issue by machinesmith42** [EvModder/DropHeads#15]

**Comment by EvModder** [comment]
Is the baby texture different from the adult?

**Comment by machinesmith42** [comment]
https://images.app.goo.gl/CKoe5xkAcDbBAngx7

**Comment by EvModder** [comment]
https://minecraft-heads.com/custom-heads/monsters/18142-zombie-pigman-skull

**Comment by machinesmith42** [comment]
yes

**Comment by machinesmith42** [comment]
will pr

**Comment by EvModder** [comment]
Nearly done with this on my end, just making sure that setting for server owners to replace all existing pigmen heads with zombified piglin heads it working for it.

**Comment by EvModder** [comment]
(Done)
