### ISSUE TITLE
Beta 3.4.1 Version, Heads aren't dropping at all

### ISSUE THREAD

**Issue by PurpleValkyrie** [EvModder/DropHeads#20]
We were trying to switch to the newer version of DropHeads so we could have the announcements for wither skeletons turn off, and when we were testing, the heads weren't dropping at all. We tested with the default config and the edited one and both had the same result. We then tested with the older jar and it worked as intended. Plugins on test world were DropHeads and World Edit. 

Is there anything else we can try to fix the issue?

**Comment by EvModder** [comment]
Hey so sorry about this... There was a bug in the v3.4.1 release. I deleted the jar from website, and uploaded a v3.4.2, but it may take a day or two to process. In the meantime, you can switch back to v3.4.0 if you want.

**Comment by PurpleValkyrie** [comment]
All good! Our server is just a big fan of the announcements and we're waiting for the new jar so we can turn them back on. Just making sure there wasn't something we were missing. Thanks for the response
