### ISSUE TITLE
Beta 3.4.2 - Config option to turn off specific mob not working

### ISSUE THREAD

**Issue by PurpleValkyrie** [EvModder/DropHeads#21]
The wither skeleton heads are showing the notification on kill in chat regardless of chat setting

\# How to announce beheadings, options are GLOBAL, LOCAL, DIRECT, or OFF
behead-announcement:
  default: 'GLOBAL'
  player: 'GLOBAL'
  wither_skeleton: 'OFF'

**Comment by EvModder** [comment]
Hmm, I haven't been able to replicate this bug, are you sure the line is uncommented and spelled correctly?

**Comment by PurpleValkyrie** [comment]
I used the default config option for wither skeletons, I just uncommented it

**Comment by EvModder** [comment]
Try re-downloading the v3.4.2 jar, and re-generating the config again?
If it still doesn't work, let me know. However, it seems to work for me (I'm testing on 1.16.x using that jar).

**Comment by EvModder** [comment]
Closing because this issue is old (and I was unable to recreate)
