### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by ElectricEzo** [EvModder/DropHeads#22]
I don't know what is causing this issue, but I can say I am running the latest version of paper (git-Paper-178, MC: 1.16.2). Also, I had the plugin folder, but deleted it because of the recent changes made so in theory it would regenerate the folder with the new jar file. But, whenever I restart the server, I get this error.

01.09 05:48:06 [Server] INFO [DropHeads] Enabling DropHeads v3.4.2
01.09 05:48:06 [Server] ERROR Error occurred while enabling DropHeads v3.4.2 (Is it up to date?)
01.09 05:48:06 [Server] INFO java.lang.IllegalStateException: zip file closed
01.09 05:48:06 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_242]
01.09 05:48:06 [Server] INFO at net.evmodder.EvLib.FileIO.installedEvPlugins(FileIO.java:47) ~[?:?]
01.09 05:48:06 [Server] INFO at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:57) ~[?:?]
01.09 05:48:06 [Server] INFO at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:21) ~[?:?]
01.09 05:48:06 [Server] INFO at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
01.09 05:48:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
01.09 05:48:06 [Server] INFO [DropHeads] Disabling DropHeads v3.4.2

**Comment by EvModder** [comment]
Ah, this happens when DropHeads is checking for add-on plugins... sometimes, other jars in the /plugins/ folder are compressed in a weird way. I've never been able to recreate this myself (because I don't know what other plugins people use that trigger this), but you are the 2nd or 3rd person to have this issue.

I've have a fix for it (will be in v3.4.3), but without knowing the exact file/jar causing it I'm not 100% sure it will work ¯_ (ツ)_/¯

You can possibly fix it for now by manually creating a folder named 'DropHeads' in your /plugins/ folder.

**Comment by ElectricEzo** [comment]
Just tried updating to v3.4.3 and got this when trying to do what I did for v3.4.2

10.09 21:37:30 [Server] ERROR Error occurred while enabling DropHeads v3.4.3 (Is it up to date?)
10.09 21:37:30 [Server] INFO java.lang.NoClassDefFoundError: Lcom/zachsthings/netevents/NetEventsPlugin;
10.09 21:37:30 [Server] INFO at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO at net.evmodder.EvLib.FileIO.installedEvPlugins(FileIO.java:47) ~[?:?]
10.09 21:37:30 [Server] INFO at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:57) ~[?:?]
10.09 21:37:30 [Server] INFO at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:21) ~[?:?]
10.09 21:37:30 [Server] INFO at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
10.09 21:37:30 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
10.09 21:37:30 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.zachsthings.netevents.NetEventsPlugin
10.09 21:37:30 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-189]
10.09 21:37:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
10.09 21:37:30 [Server] INFO ... 17 more

**Comment by EvModder** [comment]
Hmm okay. This is caused when DropHeads is looking for DropHeads add-on mods (such as HeadDatabase), but several people have been having this issue so I think I will just remove this feature in the next update...

In your particular case, the conflicting plugin seems to be whatever is referenced by " java.lang.NoClassDefFoundError: Lcom/zachsthings/netevents/NetEventsPlugin;"
Lots of plugins are set up in unorthodox/legacy or strange ways, so I'll just add an option to make DropHeads ignore this.

**Comment by EvModder** [comment]
Perhaps if you can give me a minimal example of what to do to re-create this crash, I could debug it and fix it properly... I would need to be able to re-create this on my test server, meaning I'd need to know what plugin is causing it to fail so I can download it and try for myself (to fix it or find out why)

**Comment by ElectricEzo** [comment]
It appears to be either PermissionsEx or im guessing ProtocolLib, as many things i find when searching "Zachsthings plugins" says something along the lines of "libcomponent".

**Comment by EvModder** [comment]
Ok I will try testing with those two and see if the error happens for me

**Comment by ElectricEzo** [comment]
Any luck?

**Comment by EvModder** [comment]
Yeah, this got fixed a while ago. Sorry for not updating here; there were duplicate bug posts for this issue and I missed this one..
