### ISSUE TITLE
Plugin not starting - unrelated to the other issue i think.

### ISSUE THREAD

**Issue by Hybes** [EvModder/DropHeads#23]
Fresh install of the plugin with no config:

Enabling DropHeads v3.4.4
29.09 12:36:30 [Server] WARN Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
29.09 12:36:30 [Server] ERROR Error occurred while enabling DropHeads v3.4.4 (Is it up to date?)
29.09 12:36:30 [Server] INFO java.lang.NoClassDefFoundError: Lio/lumine/xikage/mythicmobs/mobs/MobManager;
29.09 12:36:30 [Server] INFO 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	at net.evmodder.EvLib.FileIO.installedEvPlugins(FileIO.java:47) ~[?:?]
29.09 12:36:30 [Server] INFO 	at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:57) ~[?:?]
29.09 12:36:30 [Server] INFO 	at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:21) ~[?:?]
29.09 12:36:30 [Server] INFO 	at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
29.09 12:36:30 [Server] INFO 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
29.09 12:36:30 [Server] INFO Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.mobs.MobManager
29.09 12:36:30 [Server] INFO 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-206]
29.09 12:36:30 [Server] INFO 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
29.09 12:36:30 [Server] INFO 	... 17 more
29.09 12:36:30 [Server] INFO Disabling DropHeads v3.4.4

Here's the pastebin:
https://pastebin.com/asVZ7fSr

**Comment by EvModder** [comment]
Does this still occur with v3.4.5+?

**Comment by EvModder** [comment]
This was fixed a while ago
