### ISSUE TITLE
Permission only for my head with command /gethead

### ISSUE THREAD

**Issue by Uranusak** [EvModder/DropHeads#24]
Hello,
first I want to thank you for a nice plugin. 

With the command /gethead I can get any head, could you somehow add the possibility that the player can only give his head? Players have to kill each other to get their head, the command would be simpler and more practical.

**Comment by EvModder** [comment]
Sorry I didn't see this comment until just now, but yes this exists! Just give the player `dropheads.spawn.self` and they can use /gethead for their own head
