### ISSUE TITLE
Goats with 0, 1, or 2 horns

### ISSUE THREAD

**Issue by EvModder** [EvModder/DropHeads#32]
From the 1.17 snapshots, it looks like [goats](https://minecraft.fandom.com/wiki/Goat) will only have 1 or 0 horns on their model after ramming something, it would be nice to show this in the head texture as well.

**Comment by machinesmith42** [comment]
Bedrock only atm

**Comment by EvModder** [comment]
I forgot to mark this as closed, but it was completed in [d103723](https://github.com/EvModder/DropHeads/commit/d103723bb3772b52e0bed367a610384c7344e7c8)
