### ISSUE TITLE
Heads Drop 100% of the time, every time as server OP

### ISSUE THREAD

**Issue by Wh3at1y** [EvModder/DropHeads#41]
All of a sudden, (I think it was when we started enchanting) Zombie/Skeleton heads just started dropping like no tomorrow.
Changed the config in multiple files, edited the enchant modifier and everything. Still drops like crazy.

No other Mob Head plugins, just this one. We toned down the values in the config, and still no change...

[spawn-cause-modifiers.txt](https://github.com/EvModder/DropHeads/files/6487981/spawn-cause-modifiers.txt)
[head-drop-rates.txt](https://github.com/EvModder/DropHeads/files/6487982/head-drop-rates.txt)
[config-DropHeads.yml](https://github.com/EvModder/DropHeads/files/6487983/config-DropHeads.txt)

**Comment by EvModder** [comment]
Probably isn't a config issue in this case, but most likely a permissions thing for OPs; Check if you have the dropheads.alwaysbehead.<mob_type> permission and see if you can remove it in your permissions plugin. It should be off by default, but some permissions plugins are a bit sloppy and just give the "`*`" and "`plugin.*`" permissions to every server operator, which causes this.

The author of another head plugin, PlayerHeads (which supports 1.8+), describes it pretty well in [his comment here](https://dev.bukkit.org/projects/player-heads?comment=1074).
