### ISSUE TITLE
Conflict with HeadDatabase heads getting overridden

### ISSUE THREAD

**Issue by Eloujah** [EvModder/DropHeads#46]
When dropping or placing/breaking a HeadDatabase head, it get renamed to `Custom Player Head`.

The configuration to reproduce is the config: https://pastebin.com/udcNUBRh

If `refresh-textures` is set to `false`, then the HDB head is not modified. But the issue will happen on the mob': It gets renamed to `ENTITY|VARIANT's Head`.

One solution I was thinking was to set a dependency to HDB and directly use heads from HDB by ID, but I don't know if all the current variants exists.

**Comment by EvModder** [comment]
I think the easiest way I could fix this is just having the plugin ignore `refresh-textures` for any head that is from HDB, I can go ahead and bundle this in with the `v3.8.8` plugin update that I'm uploading today.

Another option you could do would be to disable the "`mob:entity_name`" stored lore on head by setting `show-head-type-in-lore` to `false` ([located here](https://github.com/EvModder/DropHeads/blob/master/config.yml#L108) in the config)

**Comment by EvModder** [comment]
(Note: Closing this bug as I believe it got fixed in v3.8.9)
