### ISSUE TITLE
Head collection library

### ISSUE THREAD

**Issue by machinesmith42** [EvModder/DropHeads#50]
I used advancements to keep track of which heads have yet to be collected

**Comment by EvModder** [comment]
All of the heads are currently tracked in [here in this file](https://github.com/EvModder/DropHeads/blob/master/head-textures.txt),
is there anything else that this feature request is for?

**Comment by machinesmith42** [comment]
That but in game

**Comment by EvModder** [comment]
I think this falls under the same umbrella as #98.
I agree having advancements is the best way to track them for a "checklist" of what heads are still needed.
