### ISSUE TITLE
Beheading announcements still made for non-player kills

### ISSUE THREAD

**Issue by RandomGgames** [EvModder/DropHeads#51]
behead-announcement-replaces-death-message: false
drop-for-nonplayer-kills: true
drop-for-ranged-kills: true
drop-for-indirect-kills: true
01:48:17.142 net.minecraft.class_338 Render thread [CHAT] §6Glow Squid§r was decapitated by §6Axolotl

Even though announce replaces death messages is set to false, I got a decapitation message for Axolotl.

**Comment by EvModder** [comment]
Oh, `behead-announcement-replaces-death-message` is for replacing player deaths, e.g. "Player1 was killed by Player2 using [Item]" with "Player1 was beheaded by Player2 using [Item]"...

To disable behead messages entirely, set `behead-announcement` for `default:` to `false` or change all the `message-beheaded-*` to `''`

**Comment by EvModder** [comment]
To reduce confusion with this in the future, I'll rename `behead-announcement-replaces-death-message` to `behead-announcement-replaces-player-death-message`
