### ISSUE TITLE
Crash at startup in 1.18rc3 / 1.18

### ISSUE THREAD

**Issue by LilianLem** [EvModder/DropHeads#53]
_Update : still not working in release 1.18_

Hi,

I'm using Spigot 1.18-rc3 to test plugins early for my future server, and I found out your plugin is crashing at startup.
I found things about NMS in my online searches, so it may be related to that.

The update is not officially out yet so it's not a critical problem, but here is the error in server logs to help you fixing it :
[dropheads-error-logs-2021-11-29.txt](https://github.com/EvModder/DropHeads/files/7620844/dropheads-error-logs-2021-11-29.txt)

**Comment by EvModder** [comment]
Thanks for the error message, and yeah it looks like it might be an NMS thing.  I should (probably) be able to get it fixed before the official spigot update is out

**Comment by EvModder** [comment]
Alright, I've uploaded a 1.18-ready version of the plugin to Bukkit; the queue times for plugin file uploads are a bit long right now but it should show up there shortly

**Comment by LilianLem** [comment]
Thank you for releasing this version that fast.

Indeed Bukkit seems to be quite slow reviewing community's files. Is there any way you could publish the latest jar here (GitHub release or direct link in readme) or send me the latest jar somehow ?
It would permit me to launch my new server tomorrow instead of waiting until next weekend.

**Comment by EvModder** [comment]
Sorry I've been slow as well for a few days, mainly because I noticed issues with the latest jar that I wanted to fix before uploading it here, but I've gone ahead and uploaded the latest working 1.18 compatible jar here on GitHub.

**Comment by LilianLem** [comment]
Thank you for your answer. I've downloaded the previous version yesterday and it was not working as expected, like I0u0I told you in #55, but the latest version seems to be perfectly fine in 1.18.
I'll come back to you if we have any problem on our server related to DropHeads.
