### ISSUE TITLE
[Suggestion] Add an item in the plugin that when killing a player/mob he has a 100% chance of dropping his head

### ISSUE THREAD

**Issue by thiagogebrimm** [EvModder/DropHeads#54]
It would be nice to have an item like that, you could give it to events and things like that, I think it would make the difficulty of picking up heads even more fun

**Comment by EvModder** [comment]
This could by done already with something like [this plugin which factors the "luck" potion effect into head drop chances](https://github.com/crashdemons/TrophyLuckModifier) (by adding a high luck attribute to an item), or could be done with another plugin that hooks into the ([DropHeads API for head drops](https://github.com/EvModder/DropHeads/blob/master/src/net/evmodder/DropHeads/events/HeadRollEvent.java)), so I don't know if it's necessary to code this feature into the main plugin
