### ISSUE TITLE
1.18 (PaperMc Build 54) - "Could not pass event EntityDeathEvent to DropHeads"

### ISSUE THREAD

**Issue by I0u0I** [EvModder/DropHeads#55]
For testing purposes Debug mode is on, Golden Axe multiplier was set to 300 (30000%), and enchanted with Looting 10 for good measure.

When entities which normally can lose thier heads (Creepers/Skeletons/Zombie/WitherSkeletons) are killed the result is as expected:

> [20:54:27] [Server thread/INFO]: _ql0u0lp_ issued server command: /spawnentity creeper
> [20:54:30] [Server thread/INFO]: [DropHeads] Creeper was decapitated by _ql0u0lp_
> [20:54:30] [Server thread/INFO]: [DropHeads] Dropping Head: CREEPER
> Killer: PLAYER, Weapon: GOLDEN_AXE
> Raw chance: 6.0%
> Multipliers >> Weapon: 30000.0%, Looting: 10.4622%, 
> Final drop chance: 1994.9476%

> [20:55:02] [Server thread/INFO]: _ql0u0lp_ issued server command: /spawnentity skeleton
> [20:55:04] [Server thread/INFO]: [DropHeads] Skeleton was decapitated by _ql0u0lp_
> [20:55:04] [Server thread/INFO]: [DropHeads] Dropping Head: SKELETON
> Killer: PLAYER, Weapon: GOLDEN_AXE
> Raw chance: 3.0%
> Multipliers >> Weapon: 30000.0%, Looting: 10.4622%, 
> Final drop chance: 997.4738%

However mobs which cannot usually drop their head (shown below) cause the error _"Could not pass event EntityDeathEvent to DropHeads v3.6.13"_ 

Original Error Message:

> [20:42:46] [Server thread/ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.6.13
> java.lang.ExceptionInInitializerError: null
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:511) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:561) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.attemptHeadDropEvent(EntityDeathListener.java:354) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:572) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:662) ~[DropHeads.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-54]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:863) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1707) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1623) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
> 	at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
> 	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2501) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2428) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-54]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
> 	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:133) ~[DropHeads.jar:?]
> 	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:18) ~[DropHeads.jar:?]
> 	... 36 more
> Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
> 	at java.lang.Class.getDeclaredMethod(Class.java:2675) ~[?:?]
> 	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:132) ~[DropHeads.jar:?]
> 	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:18) ~[DropHeads.jar:?]
> 	... 36 more

Subsequent Error Messages:
(Witch)

> [20:55:12] [Server thread/INFO]: _ql0u0lp_ issued server command: /spawnentity witch
> [20:55:16] [Server thread/ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.6.13
> java.lang.NoClassDefFoundError: Could not initialize class net.evmodder.EvLib.extras.NBTTagUtils
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:531) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:561) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.attemptHeadDropEvent(EntityDeathListener.java:354) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:572) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:662) ~[DropHeads.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-54]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:863) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1707) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1623) ~[?:?]
> 	at net.minecraft.world.entity.raid.Raider.die(Raider.java:175) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
> 	at net.minecraft.world.entity.raid.Raider.hurt(Raider.java:293) ~[?:?]
> 	at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
> 	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2501) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2428) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-54]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

(Sheep)

> [20:55:24] [Server thread/INFO]: _ql0u0lp_ issued server command: /spawnentity sheep
> [20:55:26] [Server thread/ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.6.13
> java.lang.NoClassDefFoundError: Could not initialize class net.evmodder.EvLib.extras.NBTTagUtils
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:511) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:561) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.attemptHeadDropEvent(EntityDeathListener.java:354) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:572) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:662) ~[DropHeads.jar:?]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-54]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:863) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1707) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1623) ~[?:?]
> 	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
> 	at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
> 	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2501) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2428) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-54]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by I0u0I** [comment]
Same issue caused when spawning in mob heads of entities which don't usually drop heads:

> [21:30:50] [Server thread/INFO]: _ql0u0lp_ issued server command: /spawnhead mob:SHEEP amount:10
> [21:30:50] [Server thread/ERROR]: null
> org.bukkit.command.CommandException: Unhandled exception executing command 'spawnhead' in plugin DropHeads v3.6.13
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2267) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2078) ~[?:?]
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2059) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
> 	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
> 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-54]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-54]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.ExceptionInInitializerError
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:531) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.commands.CommandSpawnHead.onCommand(CommandSpawnHead.java:216) ~[DropHeads.jar:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	... 21 more
> Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
> 	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:133) ~[DropHeads.jar:?]
> 	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:18) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:531) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.commands.CommandSpawnHead.onCommand(CommandSpawnHead.java:216) ~[DropHeads.jar:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	... 21 more
> Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.getTag()
> 	at java.lang.Class.getDeclaredMethod(Class.java:2675) ~[?:?]
> 	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:132) ~[DropHeads.jar:?]
> 	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:18) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:81) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.makeHeadFromTexture(HeadAPI.java:435) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:531) ~[DropHeads.jar:?]
> 	at net.evmodder.DropHeads.commands.CommandSpawnHead.onCommand(CommandSpawnHead.java:216) ~[DropHeads.jar:?]
> 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
> 	... 21 more

**Comment by EvModder** [comment]
Yeah, there appear to be a quite a few issues with the jar I uploaded on GitHub; I'm going to take it down again for now and re-upload it once it's working properly

**Comment by EvModder** [comment]
This should be fixed by the latest dev build (available on GitHub, should also show up on Bukkit sometime soon hopefully)
