### ISSUE TITLE
Drop Heads - getting 100% on everything 

### ISSUE THREAD

**Issue by vass88** [EvModder/DropHeads#59]
I appear to be getting 100% drop rates, I've not changed the ratios at all.
Any ideas ? thanks

**Comment by EvModder** [comment]
Check the FAQ on the plugin page (it's likely a permissions plugin on your server which gives server operators automatic 100% drop rates)

**Comment by EvModder** [comment]
(Closing issue so it's out of my feed -- feel free to reopen if you are still having issues and I'll do my best to help)
