### ISSUE TITLE
Error occurred while enabling DropHeads v3.3.7

### ISSUE THREAD

**Issue by chris998** [EvModder/DropHeads#6]
i am on Spigot 1.15.2

01.08 17:05:41 [Server] Server thread/INFO [DropHeads] Enabling DropHeads v3.3.7
01.08 17:05:41 [Server] Server thread/ERROR Error occurred while enabling DropHeads v3.3.7 (Is it up to date?)
01.08 17:05:41 [Server] INFO java.lang.NoClassDefFoundError: Lme/arcaniax/hdb/api/HeadDatabaseAPI;
01.08 17:05:41 [Server] INFO at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.getField0(Class.java:2975) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.Class.getField(Class.java:1701) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.FileIO.installedEvPlugins(FileIO.java:47) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:58) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:21) ~[?:?]
01.08 17:05:41 [Server] INFO at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:28) ~[?:?]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
01.08 17:05:41 [Server] INFO Caused by: java.lang.ClassNotFoundException: me.arcaniax.hdb.api.HeadDatabaseAPI
01.08 17:05:41 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-a99063f-be6aaf0]
01.08 17:05:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
01.08 17:05:41 [Server] INFO ... 17 more

**Comment by EvModder** [comment]
Will be fixed in v3.3.8...
This was an issue with the way HeadDatabase was loading Vault support (and then DropHeads was loading HeadDatabase)
you can temporarily fix this by adding Vault to your server, or using the beta v3.3.8 DropHeads jar I will roll out a proper release sometime in the next few days.

**Comment by chris998** [comment]
i did see the v3.3.8 and i tried that and it did fixed the issue.

**Comment by EvModder** [comment]
Hmm, what version of HDB are you using? I will go ahead and do some further testing and update the .jar

**Comment by chris998** [comment]
lol head Database? umm... i'm not using any. Here's all my plugins that i have on my server ( https://prnt.sc/tu4l7k ).

**Comment by EvModder** [comment]
Oh hmm strange... Perhaps try updating to v3.3.8, I fixed a lot of compatibility stuff recently so that might solve the crash you are having

**Comment by EvModder** [comment]
Other people reported this is fixed in v3.8.8 onward, so I'm closing the bug unless I hear otherwise.
