### ISSUE TITLE
[Feature] Feeding drops heads instead of killing.

### ISSUE THREAD

**Issue by hirata-estate** [EvModder/DropHeads#60]
This is a very niche feature, but I hope you add it. We use this as a datapack modification on our server. Instead of killing 'pet' mobs, specifically only cats and dogs were used for this; we made it so that feeding them dropped the heads at a specified rarity instead.

Unfortunately, datapacks do prove to be laggy, so a plugin alternative would be great.
I understand that this is a very specific case, but it would be great to have an option for animal loving plebs (like me) that would like to add head drops while still having a balance like this

Here's the modified datapack that I made if it'll be of any help. The mcfunctions are all in the catsafe folder to make it cleaner, but I modified the original files from xisumavoid's vanilla tweaks to not drop the heads when cats are killed any more.
[More Mob Heads - Cat & Dog safe! v2.9.2.zip](https://github.com/EvModder/DropHeads/files/8281399/More.Mob.Heads.-.Cat.Dog.safe.v2.9.2.zip)
.

**Comment by EvModder** [comment]
Hi, yeah sorry this is a bit too niche to include in the main plugin, but I'll try and make an add-on to make this work.

I think it would probably also need a config setting to include other pet types as well, something like this perhaps:
`feeding-triggers-drop-chance: [wolf, cat, parrot, horse, donkey, llama, trader_llama]`

**Comment by EvModder** [comment]
I went ahead and made [this extension](https://github.com/EvModder/PeacefulPetHeads/blob/master/config.yml) which should handle the feature nicely, however it required some API changes in the main plugin in order to link everything up properly.

After the next update for DropHeads is released this extension should work, I'll update here when that happens and post a link to the jar

**Comment by EvModder** [comment]
Hi! sorry it took me a while to update here; I released an Alpha version of DropHeads on Bukkit 4 days ago which fixed the API needed for the feeding pet heads extension plugin (which you can get [here](https://github.com/EvModder/PeacefulPetHeads/blob/master/PeacefulPetHeads.jar) for now, until I make a dedicate bukkit/curseforge page for it :))

**Comment by EvModder** [comment]
I've created a sub-page on the [DropHeads bukkit/curseforge here](https://dev.bukkit.org/projects/dropheads/pages/extras) for this add-on, so I think I will mark this FR as complete.
