### ISSUE TITLE
NoSuchMethodException Reflection Errors

### ISSUE THREAD

**Issue by jongames** [EvModder/DropHeads#62]
This is very weird as I do not see any mention of errors anywhere in issues or reviews for the plugin and checking the github code I do not see any changes to the method in years (meaning it has to have worked).  First this is my environment and start up script (running Purpur 1.14.4): 
```
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
```
```
/usr/lib/jvm/zulu11-ca-amd64/bin/java -server -Xmx7168M -Xms4096M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dpaper.playerconnection.keepalive=60 -Dlog4j2.formatMsgNoLookups=true -jar purpur-1.14.4.jar nogui --level-name JonGames --noconsole
```
Using the latest version from Bukkit's site (v3.7.2), I get this error:
```
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.NBTTagList.add(net.minecraft.server.v1_14_R1.NBTBase)
	at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:132) ~[?:?]
	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:99) ~[?:?]
```
Checking the classes inside of minecraft.jar I see: 
```
    public void add(int i, NBTBase nbtbase) {
        if (!this.b(i, nbtbase)) {
            throw new UnsupportedOperationException(String.format("Trying to add tag of type %d to list of %d", nbtbase.getTypeId(), this.type));
        }
    }
```
So I decided to "fix" part of your code from [here](https://github.com/EvModder/EvLib/blob/master/src/net/evmodder/EvLib/extras/NBTTagUtils.java) (still do not understand how it runs for you or anyone else since your getMethod is missing some of the parameters required for the function):
```
methodAdd = classNBTTagList.getMethod("add", int.class, realNBTBaseClass);
```
I also had to edit some other stuff to handle the integer now.  This resolves the first error on my end.  Now I get a new error: 
```
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.NBTTagString.NBTTagString(java.lang.String)
	at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
	at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:132) ~[?:?]
	at net.evmodder.EvLib.extras.NBTTagUtils.<clinit>(NBTTagUtils.java:116) ~[?:?]
	at net.evmodder.DropHeads.JunkUtils.setDisplayName(JunkUtils.java:64) ~[?:?]
	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:720) ~[?:?]
	at net.evmodder.DropHeads.commands.CommandSpawnHead.getHeadFromTargetString(CommandSpawnHead.java:361) ~[?:?]
	at net.evmodder.DropHeads.commands.CommandSpawnHead.onCommand(CommandSpawnHead.java:502) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-1.14.4.jar:git-Purpur-"cf994d7"]
	... 17 more
```
Now this one looks fine to me since I can find the exact method and see that net.minecraft.server.v1_14_R1.NBTTagString.NBTTagString(java.lang.String) exists in minecraft.jar which is the opposite of what Java itself says.  

I have like 40 or so other plugins and they all work fine with no reflection issues so I am confused why this plugin is causing this.  Thank you for reading this.

**Comment by jongames** [comment]
Also not very important but when I was fixing the first error, I ran into an issue with [this file](https://github.com/EvModder/EvLib/blob/master/src/net/evmodder/EvLib/util/IndexTreeMultiMap.java).  Some error I do not understand so I removed it which allowed me to compile without issues.

**Comment by jongames** [comment]
I fixed the second error.  I didn't check other server versions but at least for 1.14.4: NBTTagString(String) is not a method but a constructor.  Here are the changes I made: 

```
	static final RefClass classNBTTagString = ReflectionUtils.getRefClass("{nms}.NBTTagString", "{nm}.nbt.NBTTagString");
	//static final RefMethod cnstrNBTTagString = classNBTTagString.findMethod(/*static=*/true, /*return=*/classNBTTagString, /*param0=*/String.class);
	static final RefConstructor cnstrNBTTagString = classNBTTagString.getConstructor(String.class);
	static final Class<?> realNBTTagStringClass = classNBTTagString.getRealClass();
	public static final class RefNBTTagString extends RefNBTBase{
		public RefNBTTagString(String str){
			//nmsTag = cnstrNBTTagString.of(null).call(str);
			nmsTag = cnstrNBTTagString.create(str);
		}
	}
```

**Comment by EvModder** [comment]
Thanks for all the investigative work; give me a few minutes to catch up and figure out what's happening, and see if I can recreate the issue on a test server myself (waiting for paper-1.14.4 to download)... It's possible I made a change which broke the plugin for older versions of paper and I didn't notice it

**Comment by EvModder** [comment]
Ah, I think the issue comes down to this line:
https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L98
I load one version of the `add` function for Minecraft versions <= 1.16 and another version for > 1.16, but it seems this change actually happened in Minecraft version 1.14

**Comment by EvModder** [comment]
> Also not very important but when I was fixing the first error, I ran into an issue with [this file](https://github.com/EvModder/EvLib/blob/master/src/net/evmodder/EvLib/util/IndexTreeMultiMap.java). Some error I do not understand so I removed it which allowed me to compile without issues.

In regards to this; yeah there is a lot of stuff in EvLib that I exclude while compiling (I only include the files I use). I think in that particular case the issue is from me using JDK 16+ features

**Comment by jongames** [comment]
> > Also not very important but when I was fixing the first error, I ran into an issue with [this file](https://github.com/EvModder/EvLib/blob/master/src/net/evmodder/EvLib/util/IndexTreeMultiMap.java). Some error I do not understand so I removed it which allowed me to compile without issues.
> 
> In regards to this; yeah there is a lot of stuff in EvLib that I exclude while compiling (I only include the files I use). I think in that particular case the issue is from me using JDK 16+ features

I used Java 17

**Comment by EvModder** [comment]
Hmm, well I don't know what error it was giving you then, but either way you did the right thing by excluding it.
Also, thanks for noticing the `NBTTagString` constructor; I have no idea how I messed that one up, and even more confused that it somehow did not cause issues sooner

**Comment by jongames** [comment]
> Ah, I think the issue comes down to this line: https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L98 I load one version of the `add` function for Minecraft versions <= 1.16 and another version for > 1.16, but it seems this change actually happened in Minecraft version 1.14 So if I just change `"v1_16"` to `"v1_13"` it should work

But you need another parameter, the integer.  How can you call it with only one parameter?  There is an integer in minecraft's jar:
```
    public void add(int i, NBTBase nbtbase) {
        if (!this.b(i, nbtbase)) {
            throw new UnsupportedOperationException(String.format("Trying to add tag of type %d to list of %d", nbtbase.getTypeId(), this.type));
        }
    }
```
  Also I checked 1.16 too and it also requires 2 variables: an integer and a String

**Comment by jongames** [comment]
my changes here: https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L97
```
static final RefMethod methodAdd;
	static{
		if(ReflectionUtils.getServerVersionString().compareTo("v1_16") < 0){
			methodAdd = classNBTTagList.getMethod("add", int.class, realNBTBaseClass);
		}
		else{
			methodAdd = ReflectionUtils.getRefClass(AbstractList.class).getMethod("add", Object.class);
		}
	}
```
and here: https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L127 since if you just always add at index 0 then the lore Strings will be in reverse order.  So this code finds the last valid index and adds the new String there:
```
public void add(RefNBTBase tag){
			int i = 0;
			int j = 0;
			while (i >= 0) {
				try {
					Object value = methodGet.of(nmsTag).call(i);
					i++;
					j++;
				} catch (Exception e) {
					i = -1;
				}
			}

			methodAdd.of(nmsTag).call(j, tag.nmsTag);
		}
```

**Comment by EvModder** [comment]
> > Ah, I think the issue comes down to this line: https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L98 I load one version of the `add` function for Minecraft versions <= 1.16 and another version for > 1.16, but it seems this change actually happened in Minecraft version 1.14 So if I just change `"v1_16"` to `"v1_13"` it should work
> 
> But you need another parameter, the integer. How can you call it with only one parameter? There is an integer in minecraft's jar:
> 
> ```
>     public void add(int i, NBTBase nbtbase) {
>         if (!this.b(i, nbtbase)) {
>             throw new UnsupportedOperationException(String.format("Trying to add tag of type %d to list of %d", nbtbase.getTypeId(), this.type));
>         }
>     }
> ```
> 
> Also I checked 1.16 too and it also requires 2 variables: an integer and a String. So I do think 1.16 would give a similar issue to my 1.14.4. I only examined the jar, not actually running it on 1.16

You're forgetting the `add(NBTBase)` method that `NBTTagList` inherits from `AbstractList`

**Comment by jongames** [comment]
> > > Ah, I think the issue comes down to this line: https://github.com/EvModder/EvLib/blob/9a10778bd1e0b6fa0d3a9d7825a694b4029878e3/src/net/evmodder/EvLib/extras/NBTTagUtils.java#L98 I load one version of the `add` function for Minecraft versions <= 1.16 and another version for > 1.16, but it seems this change actually happened in Minecraft version 1.14 So if I just change `"v1_16"` to `"v1_13"` it should work
> > 
> > 
> > But you need another parameter, the integer. How can you call it with only one parameter? There is an integer in minecraft's jar:
> > ```
> >     public void add(int i, NBTBase nbtbase) {
> >         if (!this.b(i, nbtbase)) {
> >             throw new UnsupportedOperationException(String.format("Trying to add tag of type %d to list of %d", nbtbase.getTypeId(), this.type));
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also I checked 1.16 too and it also requires 2 variables: an integer and a String. So I do think 1.16 would give a similar issue to my 1.14.4. I only examined the jar, not actually running it on 1.16
> 
> We get the `add(NBTBase)` method without the int in `NBTTagList` from inheriting `AbstractList` (in 1.14+ NBTTagList extends AbstractList)

Thank you, I didn't see that.  Reflections are confusing since you don't really have the source code and I missed the whole inheritance thing (it was a class extended a class extended a class...... so not that easy to find)

**Comment by EvModder** [comment]
No thank you for reporting the issue :)
A [v3.7.2.1 jar is now available on Bukkit](https://dev.bukkit.org/projects/dropheads/files/3789616) so it will work again in 1.13 and 1.14
