### ISSUE TITLE
Head drops don't work for one of the players

### ISSUE THREAD

**Issue by FridgeGuy2** [EvModder/DropHeads#65]
Head drops have been working for everybody else except for one player on our server, they have killed thousands of creepers and enderman but have yet to get a head. Also the drop rate for creeper is .4% and for enderman its .5% so they should have gotten a head by now.

**Comment by EvModder** [comment]
Hmm, it could definitely be an issue but its hard to know for sure what. I see you marked as close so hopefully you figured out the cause :)
For future debugging though, I recommend running /droprate while looking at a player/mob, it will tell you which thing will impact your personal chance of getting a head for killing that mob
