### ISSUE TITLE
Can't join server on Paper 1.19 with EssentialsX

### ISSUE THREAD

**Issue by LilianLem** [EvModder/DropHeads#68]
I'm currently preparing a server update to 1.19, and it seems that it's impossible to join server if DropHeads and EssentialsX are enabled at the same time, and the problem is only occuring when Paper is used instead of Spigot.
The error screen is the same as the one shown in #67, and nothing more shows in console.

Here are the versions used :
- DropHeads : 3.7.4 (latest)
- EssentialsX : 2.19.4 (latest stable) or 2.19.5-dev+9-c6066bd (latest dev) (both affected)
- Paper : 1.19-8 (latest)

EssentialsX is not officially compatible with 1.19 yet, so it may be the problem, but I wanted to report it anyway so that you know it happens and you can eventually investigate on your side.

**Comment by EvModder** [comment]
Thanks for letting me know; I'll try it out and see if it's something I can easily fix (hopefully)

**Comment by EvModder** [comment]
I just tested with EssentialsX-2.19.4.jar and DropHeads v3.7.5 (my development build) on paper 1.19-8, and I didn't get the issue, so perhaps I fixed it without realizing it when I was making changes for v3.7.5.
I'm going to download the latest file for DropHeads from Bukkit and do some more tests; perhaps it only triggers for a specific configuration set

**Comment by EvModder** [comment]
@LilianLem if you want you can test with [this new jar](https://github.com/EvModder/DropHeads/blob/master/DropHeads-v3.7.5_dev.jar) and see if the issue still happens
(I'm also uploading it to Bukkit, but it can take a while to process on there)

**Comment by LilianLem** [comment]
Wow, that was fast ! It seems to work (or at least I can join the server). I'll let you know if something else happens later.
Thanks 👍
