### ISSUE TITLE
Server Crash when killing multiple mobs at a time.

### ISSUE THREAD

**Issue by I0u0I** [EvModder/DropHeads#69]
Minecraft 1.19, Purpur Build 1718 (Latest Build).

Simple zombie grinder, killing multiple zombie mobs at same time, can manage a couple of swings with no issues however after a few groups of mobs are killed the server crashes with the following errors.

Crashlog below

> [22:42:11] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1718 (MC: 1.19) ---
> [22:42:11] [Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
> [22:42:11] [Watchdog Thread/ERROR]: ------------------------------
> [22:42:11] [Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
> [22:42:11] [Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.EntityPlayer
> [22:42:11] [Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
> [22:42:11] [Watchdog Thread/ERROR]: Entity UUID: e382bf17-c085-46cd-aabd-a31be1051fc9
> [22:42:11] [Watchdog Thread/ERROR]: Position: world: 'world' at location (-292.76539917999196, 68.0, 113.05048578261285)
> [22:42:11] [Watchdog Thread/ERROR]: Velocity: (0.0, -0.0784000015258789, 0.0) (in blocks per tick)
> [22:42:11] [Watchdog Thread/ERROR]: Entity AABB: AABB[-293.0653991919129, 68.0, 112.75048577069192] -> [-292.46539916807103, 69.79999995231628, 113.35048579453378]
> [22:42:11] [Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 4096
> [22:42:11] [Watchdog Thread/ERROR]: ------------------------------
> [22:42:11] [Watchdog Thread/ERROR]: Current Thread: Server thread
> [22:42:11] [Watchdog Thread/ERROR]: 	PID: 28 | Suspended: false | Native: false | State: RUNNABLE
> [22:42:11] [Watchdog Thread/ERROR]: 	Stack:
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils$Component.potentialSingleMatchSelector(TellrawUtils.java:177)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils$Component.potentialSingleMatchSelector(TellrawUtils.java:177)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils$Component.isPropertiesSupersetOf(TellrawUtils.java:227)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils$ListComponent.addComponent(TellrawUtils.java:626)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseListComponent(TellrawUtils.java:829)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseNextComponentFromString(TellrawUtils.java:1069)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseListComponent(TellrawUtils.java:827)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseNextComponentFromString(TellrawUtils.java:1069)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseListComponent(TellrawUtils.java:827)
> 
> ... ### Repeats for 350 lines ### ...
>
>[22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.EvLib.extras.TellrawUtils.parseComponentFromString(TellrawUtils.java:1077)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.JunkUtils.getMurderItemComponent(JunkUtils.java:172)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.DropChanceAPI.getWeaponComponent(DropChanceAPI.java:535)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.DropChanceAPI.getBeheadMessage(DropChanceAPI.java:550)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:686)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:175)
> [22:42:11] [Watchdog Thread/ERROR]: 		DropHeads.jar//net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:268)
> [22:42:11] [Watchdog Thread/ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
> [22:42:11] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [22:42:11] [Watchdog Thread/ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:677)
> [22:42:11] [Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:886)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1803)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1698)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1515)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.world.entity.player.Player.attack(Player.java:1390)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2181)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2813)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2738)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$9622/0x00000008028dc258.run(Unknown Source)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
> [22:42:11] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4526/0x0000000801557b00.run(Unknown Source)
> [22:42:11] [Watchdog Thread/ERROR]: 		java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
> [22:42:11] [Watchdog Thread/ERROR]: ------------------------------
> [22:42:11] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
> [22:42:11] [Watchdog Thread/ERROR]: ------------------------------

**Comment by I0u0I** [comment]
Update:
The cause appears to be the plugin "EcoReforges", adding a load of shit to the item name NBT data of the weapon

> {Name: '{"italic":false,"extra":[{"italic":false,"extra":[{"translate":"item.minecraft.netherite_sword"}],"text":""}],"text":""} 

and dropheads shitting the bed when trying to translate that to english.

While this issue isn't directly caused by dropheads, and should not happen in normal use I'm leaving it open in case you choose to use it to throw in extra error checking.

**Comment by EvModder** [comment]
Thanks for reporting it and sorry I didn't respond until now.. it definitely looks like some kind of infinite loop bug that probably exists in the library DropHeads uses to parse/translate the NBT text json message formatting from a raw string, so definitely something I want to fix.

I'll continue to leave the bug open until it is resolved, just wanted to give an acknowledgement/update comment

**Comment by EvModder** [comment]
Actually, if you have any more example item name NBTs like the one you shared in [comment#2](https://github.com/EvModder/DropHeads/issues/69#issuecomment-1189548575), it could be helpful for debugging (I've been trying to recreate the issue for myself by spamming the library with NBTs like the ones causing the issue)

**Comment by EvModder** [comment]
I think one "lazy" fix I can do for this is caching the `TextComponent` generated for behead weapons, I'll add an option for it in the config. That way if a bunch of beheads are happening back-to-back using the same weapon, it won't need to recompute it for each behead message

**Comment by EvModder** [comment]
I ended up implementing the fix described above, so this *should* in theory be fixed now (but please comment or re-open if it still occurs for you)
