### ISSUE TITLE
Player heads fail to drop when an inventory protection plugin is enabled

### ISSUE THREAD

**Issue by itsgaryk** [EvModder/DropHeads#7]
**Server used**
PaperMC build 130

**Plugins used**
BackupOnEvent*, ConsoleSpamFix, DeadChest, DiscordSRV, DropHeads, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, GriefPrevention, InstantBreak*, LuckPerms, Pingas*, PlugMan, ProtocolLib, SilkSpawners, SmoothSleep, uShop, Vault, WorldEdit

I am using the following plugin:
https://dev.bukkit.org/projects/dead-chest

When a player is killed it drops a chest for them to collect and prevents the head from dropping.

I tested with another player. After killing me I collected my Dead Chest and it contained the head of another player.

If possible could you implement a method to bypass inventory protection plugins like Dead Chest or add a setting so the head goes straight into another players inventory, maybe include a condition to drop the head if the killing player has a full inventory

**Comment by EvModder** [comment]
Yeah, this has been a requested feature (and is planned for a near-future update).
This issue is mainly DeadChest's fault IMO, but still something I can fix from the DropHeads side.

**Comment by EvModder** [comment]
@itsgaryk There may be a workaround in the DropHeads v3.4.0 release, but I haven't tested it yet.
Basically, DeadChest and DropHeads both listen to the "EntityDeathEvent" and modify it:
* DropHeads adds the head to the list of items that will be dropped
* DeadChest takes the list of items to be dropped and puts them in a chest

The issue is that DropHeads runs before DeadChest... I don't think DeadChest has a config option to change the listener priority (aka order) of its code, but with DropHeads v3.4.0 you can change "death-listener-priority: LOW" in the config.yml to HIGH, HIGHEST, or MONITOR and see if that works as a fix

**Comment by itsgaryk** [comment]
That's great to hear. I'll test and will let you know the results with the parameter:

**from**
death-listener-priority: LOW
**to**
death-listener-priority: HIGHEST

**Comment by EvModder** [comment]
Yeah, the Bukkit configuration file system isn't great... To get plugins to update config files, you need to delete the existing config file and let it re-generate a new one (I would recommend just renamed it to something like config-DropHeads.yml_backup, and then copying over settings you care about)

**Comment by EvModder** [comment]
Any luck with the priority setting btw?
If not, I can just make it drop items separately from the EntityDeathEvent, although that will be a bit less clean.

Or I could see about modifying the DeadChest plugin, maybe I could convince the author to accept some changes. I've looked at the code and it looks like it would be really easy to fix on their end

**Comment by HiMyNameIsBoxxy** [comment]
Hello! I am using a plugin called Graves. It spawns a chest when a player dies and puts everything in there. I have tried both MONITOR and LOWEST to see if headrop will react faster than Graves but unfortunately, it didn't. Anyway to fix this?

**Comment by EvModder** [comment]
Hi, sorry for the late reply... I added a setting called `drop-mode` several months ago that you can use to bypass plugins like that, in case you were still looking :)
