### ISSUE TITLE
Issue upon startup.

### ISSUE THREAD

**Issue by Spruce-Studios** [EvModder/DropHeads#71]
I've been using dropheads for one week now (the latest version).
When I restart my server, I get this error message:

`05.08 01:43:06 [Server] INFO Enabling DropHeads v3.7.6
05.08 01:43:06 [Server] WARN Relocating data in ./plugins/DropHeads/, this might take a minute..
05.08 01:43:07 [Server] ERROR Error occurred while enabling DropHeads v3.7.6 (Is it up to date?)
05.08 01:43:07 [Server] INFO java.lang.UnsupportedOperationException: Unsupported copy option
05.08 01:43:07 [Server] INFO at sun.nio.fs.UnixCopyFile$Flags.fromMoveOptions(UnixCopyFile.java:116) ~[?:?]
05.08 01:43:07 [Server] INFO at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:403) ~[?:?]
05.08 01:43:07 [Server] INFO at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267) ~[?:?]
05.08 01:43:07 [Server] INFO at java.nio.file.Files.move(Files.java:1432) ~[?:?]
05.08 01:43:07 [Server] INFO at net.evmodder.EvLib.FileIO.moveDirectoryContents(FileIO.java:37) ~[DropHeads.jar:?]
05.08 01:43:07 [Server] INFO at net.evmodder.EvLib.FileIO.verifyDir(FileIO.java:75) ~[DropHeads.jar:?]
05.08 01:43:07 [Server] INFO at net.evmodder.EvLib.EvPlugin.reloadConfig(EvPlugin.java:20) ~[DropHeads.jar:?]
05.08 01:43:07 [Server] INFO at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:28) ~[DropHeads.jar:?]
05.08 01:43:07 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
05.08 01:43:07 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
05.08 01:43:07 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
05.08 01:43:07 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:420) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
05.08 01:43:07 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
05.08 01:43:07 [Server] INFO Disabling DropHeads v3.7.6`

None of the commands work, and mobs won't drop their heads. Please help, this is one of the main features of my server!

**Comment by EvModder** [comment]
Sorry for the slow response. I assume you are the same person who reported this issue on Bukkit?
The solution for now would be to remove or update ChatManager ([update here](https://github.com/EvModder/ChatManager/releases/tag/v2.1.1) and delete the "EvFolder" it is trying to create...

This issue was caused by some old legacy code I had in ChatManager and some other plugins which tried to put all the configuration files for my plugins into one folder because I felt my /plugins/ directory was getting too big/spammy, but it turned out to cause way more problems than I ever expected and even though I stopped doing it 10 years ago sometimes my old plugins are still hanging around and it does this
