### ISSUE TITLE
Could not pass event HangingBreakByEntityEvent to DropHeads

### ISSUE THREAD

**Issue by KioProject123** [EvModder/DropHeads#80]
https://paste.gg/p/anonymous/360242fe31f540248646ed78beab2316

I am using the purpur of 1.19.2, it happened this error

**Comment by EvModder** [comment]
Alright, I've gotten a fix working for the upcoming version (next update) for DropHeads, in the meantime I suggest adding `ITEM_FRAME: 0.0` to the [head-drop-rates.txt](https://github.com/EvModder/DropHeads/blob/master/head-drop-rates.txt) file in your config folder to prevent this error

**Comment by EvModder** [comment]
The next update on DropHeads is out, which should fully fix this issue now (I added a "missing texture" texture for mob heads with missing textures, lol)
