### ISSUE TITLE
Use axe only

### ISSUE THREAD

**Issue by StefthePirate91** [EvModder/DropHeads#84]
Use axe only true

Doesnt work for me.

and what number is 100% drop chance?

**Comment by EvModder** [comment]
You're talking about [this setting](https://github.com/EvModder/DropHeads/blob/0eafcd803fa9fc6fdea5fe558fd477e8a7616ec3/config.yml#L129) right?
When it is set to true, players will only be able to get heads from mobs/players by killing them with an axe, although I think there might be some permissions that bypass this.

As for getting 100% drop chance, you can just set the contents of file like this:
**head-drop-rates.txt**:
```
DEFAULT: 1

ARMOR_STAND: 0
LEASH_HITCH: 0
MINECART: 0
MINECART_CHEST: 0
MINECART_COMMAND: 0
MINECART_FURNACE: 0
MINECART_HOPPER: 0
MINECART_MOB_SPAWNER: 0
MINECART_TNT: 0
```
**spawn-cause-modifiers.txt**:
```<delete everything in this file so it is empty>```
