### ISSUE TITLE
Boats, Itemframes etc. drop null head

### ISSUE THREAD

**Issue by derech1e** [EvModder/DropHeads#85]
When you destroy a Boat or an other entity with your hand in the latest version, they drop a curious head.

**Comment by EvModder** [comment]
Yeah, this was an intended change, previously it gave an error in the console for "missing head texture"

I see you marked the bug as closed so you probably figured out the workaround, but I'll post it here just in case for anyone that finds this bug --
The simplest way to avoid this is to set the [dropchance](https://github.com/EvModder/DropHeads/blob/master/head-drop-rates.txt) to 0 for all entities which don't have a texture or shouldn't have a head drop on your server (mainly boats, item frames, minecart-with-chest, etc)
