### ISSUE TITLE
Main Thread API Call Crash

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [EvModder/DropHeads#93]
Here's the crash log: https://mclo.gs/8eUAVEs

**Comment by EvModder** [comment]
Hmm.. can you give me the steps to recreate this?
(I.e., what settings or other plugins are needed, plus what player action sequence to trigger the crash)

Otherwise, I can try and look into it, but at the moment I'm having trouble finding any issues in the code.

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> Hmm.. can you give me the steps to recreate this? (I.e., what settings or other plugins are needed, plus what player action sequence to trigger the crash)
> 
> Otherwise, I can try and look into it, but at the moment I'm having trouble finding any issues in the code.

I have no idea. It happened once and completely randomly.

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> Hmm.. can you give me the steps to recreate this? (I.e., what settings or other plugins are needed, plus what player action sequence to trigger the crash)
> 
> Otherwise, I can try and look into it, but at the moment I'm having trouble finding any issues in the code.

I mean you could perhaps make api calls async

**Comment by EvModder** [comment]
OH, yeah I did that in v3.7.10, which is not published on Bukkit yet but it's available on this GitHub. That's probably the cause of this tbh

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> OH, yeah I did that in v3.7.10, which is not published on Bukkit yet but it's available on this GitHub. That's probably the cause of this tbh

Where do I find it though without compiling code ?

**Comment by EvModder** [comment]
It's posted [here](https://github.com/EvModder/DropHeads/blob/master/DropHeads_v3.7.10.jar), but I also uploaded it to Bukkit just now so it should be available there within a day or two once it finishes processing.

**Comment by EvModder** [comment]
@RAINRAINRAINRAINRAINRAINRAINRAINRAIN I found a big part of the reason for this issue, which I originally missed, specifically for custom mob heads.

It should be been fixed now ([v3.9.0+](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.9.0.jar))
