### ISSUE TITLE
The player's head does not display the player's name

### ISSUE THREAD

**Issue by KioProject123** [EvModder/DropHeads#95]
Use default configuration
![image](https://user-images.githubusercontent.com/61594596/226165040-62392f5e-10f7-4ed6-a264-df23208ae7c8.png)

Set `show-head-type-in-lore: false`
![image](https://user-images.githubusercontent.com/61594596/226165063-c8049e50-354b-4738-859e-af71b09c8295.png)

This is normal in 3.7.9. 
![image](https://user-images.githubusercontent.com/61594596/226165228-46c906bb-05f7-4321-83fe-972c934e4338.png)
But something went wrong when I updated to 3.7.11.

**Comment by EvModder** [comment]
Pinpointed the issue and was able to get it fixed!
I'll roll out v3.7.12 sometime tonight or tomorrow (which will include this)
